name: deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Deploy common
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Ccode
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: npm ci
      - name: Configure Github
        run: |
          git config --global user.name 'Mike Bates'
          git config --global user.email 'mike@bates-solutions.com'
      - name: Update Version
        run: npm version minor
      - name: Update Version on Github
        run: git push
      - name: Build
        run: npm run build
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
