version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/example"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/example"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/common"
    schedule:
      interval: "weekly"
