version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/auth"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/auth"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/sample-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/sample-service"
    schedule:
      interval: "weekly"
