apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infrastructure/k8s/*
    - ./infrastructure/k8s-local/*
build:
  local:
    push: true
  artifacts:
    - image: batessolutions/example-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: batessolutions/example-service
      context: service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
