apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-service
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
        - name: sample-service
          image: batessolutions/example-sample-service
          env:
            - name: NATS_CLUSTER_ID
              value: example-cluster
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service-srv
spec:
  selector:
    app: sample-service
  ports:
    - name: sample-service
      protocol: TCP
      port: 3000
      targetPort: 3000
